services:

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-enterprise
    networks:
      - localprom
    ports:
      - "3001:3000"   
    depends_on:
      - prometheus
networks:
  localprom:
    driver: bridge