version: '3.4'

services:

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=longrunning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432