services:

 # The .NET APP
  oi.web.services:
    image: oiwebservices
    #network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      #- "8001:8001"
