services:

 # The .NET APP
  oi.web.services:
    image: oiwebservices
    #network_mode: host
    build:
      context: .
      dockerfile: DockerfileWebServices
    ports:
      - "8000:8000"

  oi.jobprocessing:
    image: oijobprocessing
    #network_mode: host
    build:
      context: .
      dockerfile: DockerfileJobProcessing
    ports:
      - "8005:8005"